name: Bump version

on:
  workflow_call:
    outputs:
      new_ver:
        description: New version number
        value: ${{ jobs.bump_version.outputs.new_tag }}


jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bumper.outputs.new_ver }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: bumper
        uses: jasonamyers/github-bumpversion-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
