# Shortcut that runs both
# * bump-version.yml
# * push-docker.yml

name: Bump version and auto-release

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      PAT_TOKEN:
        required: true
    inputs:
      image_base_name:
        required: true
        type: string
      docker_file:
        required: false
        type: string
        default: Dockerfile

jobs:
  bump-version:
    # temp branch name
    uses: openclimatefix/.github/.github/workflows/bump-version.yml@clean-up
    secrets: inherit

  docker-release:
    needs: [bump-version]
    uses: openclimatefix/.github/.github/workflows/push-docker.yml@clean-up
    with:
      image_base_name: ${{inputs.image_base_name}}
      docker_file: ${{inputs.docker_file}}
      tag_value: ${{ needs.bump-version.outputs.new_ver }}
    secrets: inherit
