name: Bump version and auto-release

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      image_base_name:
        required: true
        type: string
      docker_file:
        required: false
        type: string
        default: Dockerfile

jobs:
  bump-version:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/bump-version.yml

  docker-release:
    needs: [bump-version]
    runs-on: ubuntu-latest
    uses: ./.github/workflows/docker-release-only.yml
    with:
      image_base_name: ${{inputs.image_base_name}}
      docker_file: ${{inputs.docker_file}}
      tag_value: ${{ needs.bump-version.outputs.new_tag }}
    secrets: inherit
