name: Bump version and auto-release
on:
  workflow_call:
    secrets:
      token:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      image_base_name:
        required: true
        type: string
      docker_file:
        required: false
        type: string
        default: Dockerfile

jobs:
  bump_version:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/bump-version.yml

  build:
    needs: [bump_version]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.token }}

  python-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.bump_version.outputs.new_tag}}
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.new_tag }}
          release_name: v${{ needs.build.outputs.new_tag }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

  docker-release:
    needs: [build, python-release]
    runs-on: ubuntu-latest
    uses: ./.github/workflows/docker-release-only.yml
    with:
      image_base_name: ${{inputs.image_base_name}}
      docker_file: ${{inputs.docker_file}}
      tag_value: ${{ needs.ptate.outputs.new_tag }}
    secrets: inherit
